language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11

addons:
    sonarcloud:
        organization: "robstoll-github"
        token:
            secure: $SONAR_TOKEN

before_install:
 - chmod +x gr
install: true

script:
  - ./gr -i build detekt
  - |
    if [ "$TRAVIS_TEST_RESULT" == 0 ] && [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
        sonar-scanner \
            -Dsonar.projectVersion=0.13.0 \
            -Dsonar.projectKey=robstoll_kbox \
            -Dsonar.kotlin.detekt.reportPaths=build/detekt/detekt-checkstyle.xml \
            -Dsonar.sources="\
                kbox-android/src/main/kotlin, \
                kbox-common/src/main/kotlin,\
                kbox-js/src/main/kotlin,\
                kbox-jvm/src/main/kotlin" \
            -Dsonar.tests=kbox-jvm/src/test/kotlin
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/
